
import os
import shutil
import json
from datetime import datetime
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from openpyxl import load_workbook #imports python library for reading and writting excel files
from openpyxl.drawing.image import Image

def create_weekly_report_folder():

    while True:
        week_start = input("Enter Week Start Date (mm-dd-yyyy): ")

        try:
            formatted_week_start = datetime.strptime(week_start, "%m-%d-%Y")
            break
        except ValueError:
            print("Invalid date format. Please use mm-dd-yyyy.")
        
    
    year = formatted_week_start.year
    month = formatted_week_start.strftime("%m_%B")
    

    week_folder = f"{week_start}_weekly_report"
    invoices_reports_folder = "invoices_reports"
    charts_folder = "charts"

    event_financial_reports_folder = Path("event_financial_reports")

    week_folder_path = event_financial_reports_folder / str(year) / month / week_folder
    invoices_reports_path = week_folder_path / invoices_reports_folder
    charts_path = week_folder_path / charts_folder

    # Create a new weekly folder provided the following folders exist:  event_financial_reports_folder / year / month
    week_folder_path.mkdir(parents=True, exist_ok=True)

    # Creates a folder for invoices and labor reports for the week => invoices_reports
    invoices_reports_path.mkdir(parents=True, exist_ok=True)

    # Creates a folder for .png files generated by matplotlib  => charts
    charts_path.mkdir(parents=True, exist_ok=True)

# Copies a .json weekly data input file into a folder named after the week.
    weekly_data_path = Path("weekly_data.json")

    if weekly_data_path.exists():
        new_weekly_data = f"{formatted_week_start.strftime('%m-%d-%Y')}_weekly_data.json"
        try:
            shutil.copy2(weekly_data_path,  week_folder_path)
        except OSError as e:
            print(f"Could not copy weekly_data.json: {e}")
    else:
        print("weekly_data.json template not found.")
        

# Copies a WEEKLY REPORTING TEMPLATE into a folder named after the week.
    weekly_template_path = Path("WEEKLY REPORTING TEMPLATE.xlsx")

    if weekly_template_path.exists():
        report_name = f"{formatted_week_start.strftime('%m-%d-%Y')}_weekly_report.xlsx"
        report_dest = week_folder_path / report_name

        try:
            shutil.copy2(weekly_template_path, report_dest)
        except OSError as e:
            print(f"Could not copy weekly template: {e}")
    else:
        print("weekly_event_reporting_template.xlsx not found.")
